#!/usr/bin/env sh

echo "###############################"
echo "# Building images"
echo "###############################"

while read -r tagname no_root_mode docker_version compose_version awscli_version terraform_version;
do
  image=${DOCKER_REPO}:${tagname}
  echo "# Building image ${image}..."

  cmd="docker build \
    --build-arg DOCKER_VERSION="${docker_version}" \
    --build-arg COMPOSE_VERSION="${compose_version}" \
    --build-arg AWSCLI_VERSION="${awscli_version}" \
    --build-arg TERRAFORM_VERSION="${terraform_version}" \
    --build-arg NO_ROOT_MODE="${no_root_mode}" \
    --pull \
    -t "${image}" ."

  echo "# Building command : ${cmd}"

  ${cmd}

  echo "-------------------------------"
done < VERSIONS_MATRIX