#!/usr/bin/env sh

set -ex

while read -r tagname docker_version compose_version awscli_version terraform_version;
do
  image=${DOCKER_REPO}:${tagname}
  echo "# Building image ${image}..."

  docker build \
    --build-arg DOCKER_VERSION="${docker_version}" \
    --build-arg COMPOSE_VERSION="${compose_version}" \
    --build-arg AWSCLI_VERSION="${awscli_version}" \
    --build-arg TERRAFORM_VERSION="${terraform_version}" \
    --pull \
    -t "${image}" .
done < VERSIONS_MATRIX