#!/usr/bin/env sh

set -ex

i=1
while read -r tagname docker_version compose_version awscli_version terraform_version;
do
  test $i -eq 1 && ((i=i+1)) && continue
  
  image=${DOCKER_REPO}:${tagname}
  echo "# Pushing image ${image}..."

  docker image push "${image}"
done < VERSIONS_MATRIX
