#!/usr/bin/env sh

set -ex

while read -r tagname docker_version compose_version awscli_version terraform_version;
do
  image=${DOCKER_REPO}:${tagname}
  echo "# Pushing image ${image}..."

  docker image push "${image}"
done < VERSIONS_MATRIX
