#!/usr/bin/env sh

echo "###############################"
echo "# Pushing images"
echo "###############################"

while read -r tagname no_root_mode docker_version compose_version awscli_version terraform_version;
do
  image=${DOCKER_REPO}:${tagname}
  echo "# Pushing image ${image}..."

  cmd="docker image push "${image}""

  echo "# Pushing command : ${cmd}"

  ${cmd}

  echo "-------------------------------"
done < VERSIONS_MATRIX
