#!/usr/bin/env sh

set -ex

i=1
while read -r tagname docker_version compose_version awscli_version terraform_version;
do
  test $i -eq 1 && ((i=i+1)) && continue
  
  image=${DOCKER_REPO}:${tagname}
  echo "# Testing image ${image}..."
  export IMAGE_NAME="${image}"

  container=$(docker-compose -f docker-compose.test.yml run -d sut)

  if [ "$(docker container wait "${container}")" != "0" ]
  then
    echo "Test of ${IMAGE_NAME} failed"
    exit 1
  fi
  docker-compose -f docker-compose.test.yml rm --force sut
done < VERSIONS_MATRIX
