#!/usr/bin/env sh

echo "###############################"
echo "# Testing images"
echo "###############################"

while read -r tagname no_root_mode docker_version compose_version awscli_version terraform_version;
do
  image=${DOCKER_REPO}:${tagname}
  echo "# Testing image ${image}..."
  export IMAGE_NAME="${image}"

  container=$(docker-compose -f docker-compose.test.yml run -d sut)

  if [ "$(docker container wait "${container}")" != "0" ]
  then
    echo "Test of ${IMAGE_NAME} failed"
    exit 1
  fi
  docker-compose -f docker-compose.test.yml rm --force sut

  echo "-------------------------------"
done < VERSIONS_MATRIX
